DROP TABLE IF EXISTS DIFFICULTE;
DROP TABLE IF EXISTS JOUEUR;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS FILM_GENRE;
DROP TABLE IF EXISTS FILM;

CREATE TABLE DIFFICULTE(nom VARCHAR(255) NOT NULL PRIMARY KEY);

CREATE TABLE  JOUEUR (
     id_joueur INTEGER PRIMARY KEY AUTOINCREMENT ,
     Nom  VARCHAR(255) NOT NULL,
     score  INTEGER NOT NULL
);
CREATE TABLE  Genre ( nom  VARCHAR(255) NOT NULL PRIMARY KEY);

CREATE TABLE  FILM (
     id_film  INTEGER PRIMARY KEY AUTOINCREMENT,
     Image  LINESTRING NOT NULL,
     Nom  VARCHAR(255) NOT NULL,
     Description  MULTILINESTRING NULL,
     difficulte  VARCHAR(255) NOT NULL,
    FOREIGN KEY( difficulte ) REFERENCES  DIFFICULTE ( nom )
);
CREATE TABLE  FILM_GENRE (
     id_film  INTEGER NOT NULL,
     genre  VARCHAR(255) NOT NULL,
     FOREIGN KEY (id_film) REFERENCES FILM(id_film),
     FOREIGN KEY (genre) REFERENCES Genre(nom)
);
