CREATE TABLE `DIFFICULTE`(`nom` VARCHAR(255) NOT NULL);
ALTER TABLE
    `DIFFICULTE` ADD PRIMARY KEY(`nom`);
CREATE TABLE `JOUEUR`(
    `id_joueur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Nom` VARCHAR(255) NOT NULL,
    `score` INT UNSIGNED NOT NULL
);
ALTER TABLE
    `JOUEUR` ADD PRIMARY KEY(`id_joueur`);
CREATE TABLE `Genre`(`nom` VARCHAR(255) NOT NULL);
ALTER TABLE
    `Genre` ADD PRIMARY KEY(`nom`);
CREATE TABLE `FILM_GENRE`(
    `id_film` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `genre` VARCHAR(255) NOT NULL
);
CREATE TABLE `FILM`(
    `id_film` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Image` LINESTRING NOT NULL,
    `Nom` VARCHAR(255) NOT NULL,
    `Description` MULTILINESTRING NULL,
    `difficulté` VARCHAR(255) NOT NULL
);
ALTER TABLE
    `FILM` ADD PRIMARY KEY(`id_film`);
ALTER TABLE
    `FILM` ADD CONSTRAINT `film_difficulté_foreign` FOREIGN KEY(`difficulté`) REFERENCES `DIFFICULTE`(`nom`);
ALTER TABLE
    `FILM_GENRE` ADD CONSTRAINT `film_genre_id_film_foreign` FOREIGN KEY(`id_film`) REFERENCES `FILM`(`id_film`);
ALTER TABLE
    `FILM_GENRE` ADD CONSTRAINT `film_genre_genre_foreign` FOREIGN KEY(`genre`) REFERENCES `Genre`(`nom`);